import addConsumer from "./abis/addConsumer.json";
import approve from "./abis/approve.json";
import balanceOf from "./abis/balanceOf.json";
import blacklist from "./abis/blacklist.json";
import breed from "./abis/breed.json";
import claim from "./abis/claim.json";
import craft from "./abis/craft.json";
import createSubscription from "./abis/createSubscription.json";
import deployCollection from "./abis/deployCollection.json";
import deployERC1155Token from "./abis/deployERC1155Token.json";
import deployERC20Token from "./abis/deployERC20Token.json";
import deployERC721Token from "./abis/deployERC721Token.json";
import deployERC998Token from "./abis/deployERC998Token.json";
import deployLottery from "./abis/deployLottery.json";
import deployMysterybox from "./abis/deployMysterybox.json";
import deployPaymentSplitter from "./abis/deployPaymentSplitter.json";
import deployPonzi from "./abis/deployPonzi.json";
import deployRaffle from "./abis/deployRaffle.json";
import deployStaking from "./abis/deployStaking.json";
import deployVesting from "./abis/deployVesting.json";
import deployWaitList from "./abis/deployWaitList.json";
import deposit from "./abis/deposit.json";
import dismantle from "./abis/dismantle.json";
import disperse from "./abis/disperse.json";
import endRound from "./abis/endRound.json";
import getERC20 from "./abis/getERC20.json";
import getPenalty from "./abis/getPenalty.json";
import getPrize from "./abis/getPrize.json";
import getSubscription from "./abis/getSubscription.json";
import grantRole from "./abis/grantRole.json";
import lend from "./abis/lend.json";
import mint from "./abis/mint.json";
import mintBox from "./abis/mintBox.json";
import mintCommon from "./abis/mintCommon.json";
import pause from "./abis/pause.json";
import purchase from "./abis/purchase.json";
import purchaseLottery from "./abis/purchaseLottery.json";
import purchaseMystery from "./abis/purchaseMystery.json";
import purchaseRaffle from "./abis/purchaseRaffle.json";
import receiveReward from "./abis/receiveReward.json";
import releasable from "./abis/releasable.json";
import release from "./abis/release.json";
import releaseFunds from "./abis/releaseFunds.json";
import renounceRole from "./abis/renounceRole.json";
import revokeRole from "./abis/revokeRole.json";
import safeTransferChild from "./abis/safeTransferChild.json";
import safeTransferFrom from "./abis/safeTransferFrom.json";
import safeTransferFromERC1155 from "./abis/safeTransferFromERC1155.json";
import setApprovalForAll from "./abis/setApprovalForAll.json";
import setDefaultRoyalty from "./abis/setDefaultRoyalty.json";
import setPregnancyLimits from "./abis/setPregnancyLimits.json";
import setReward from "./abis/setReward.json";
import setRules from "./abis/setRules.json";
import setSubscriptionId from "./abis/setSubscriptionId.json";
import startRound from "./abis/startRound.json";
import topUp from "./abis/topUp.json";
import transfer from "./abis/transfer.json";
import transferAndCall from "./abis/transferAndCall.json";
import transferERC20 from "./abis/transferERC20.json";
import transferOwnership from "./abis/transferOwnership.json";
import unBlacklist from "./abis/unBlacklist.json";
import unWhitelist from "./abis/unWhitelist.json";
import unWhitelistChild from "./abis/unWhitelistChild.json";
import unpack from "./abis/unpack.json";
import unpause from "./abis/unpause.json";
import updateRule from "./abis/updateRule.json";
import upgrade from "./abis/upgrade.json";
import userOf from "./abis/userOf.json";
import whiteListChild from "./abis/whiteListChild.json";
import whitelist from "./abis/whitelist.json";
import withdrawBalance from "./abis/withdrawBalance.json";
import withdrawToken from "./abis/withdrawToken.json";

export const addConsumerABI = addConsumer;
export const approveABI = approve;
export const balanceOfABI = balanceOf;
export const blacklistABI = blacklist;
export const breedABI = breed;
export const claimABI = claim;
export const craftABI = craft;
export const createSubscriptionABI = createSubscription;
export const deployCollectionABI = deployCollection;
export const deployERC1155TokenABI = deployERC1155Token;
export const deployERC20TokenABI = deployERC20Token;
export const deployERC721TokenABI = deployERC721Token;
export const deployERC998TokenABI = deployERC998Token;
export const deployLotteryABI = deployLottery;
export const deployMysteryboxABI = deployMysterybox;
export const deployPaymentSplitterABI = deployPaymentSplitter;
export const deployPonziABI = deployPonzi;
export const deployRaffleABI = deployRaffle;
export const deployStakingABI = deployStaking;
export const deployVestingABI = deployVesting;
export const deployWaitListABI = deployWaitList;
export const depositABI = deposit;
export const dismantleABI = dismantle;
export const disperseABI = disperse;
export const endRoundABI = endRound;
export const getERC20ABI = getERC20;
export const getPenaltyABI = getPenalty;
export const getPrizeABI = getPrize;
export const getSubscriptionABI = getSubscription;
export const grantRoleABI = grantRole;
export const lendABI = lend;
export const mintABI = mint;
export const mintBoxABI = mintBox;
export const mintCommonABI = mintCommon;
export const pauseABI = pause;
export const purchaseABI = purchase;
export const purchaseLotteryABI = purchaseLottery;
export const purchaseMysteryABI = purchaseMystery;
export const purchaseRaffleABI = purchaseRaffle;
export const receiveRewardABI = receiveReward;
export const releasableABI = releasable;
export const releaseABI = release;
export const releaseFundsABI = releaseFunds;
export const renounceRoleABI = renounceRole;
export const revokeRoleABI = revokeRole;
export const safeTransferChildABI = safeTransferChild;
export const safeTransferFromABI = safeTransferFrom;
export const safeTransferFromERC1155ABI = safeTransferFromERC1155;
export const setApprovalForAllABI = setApprovalForAll;
export const setDefaultRoyaltyABI = setDefaultRoyalty;
export const setPregnancyLimitsABI = setPregnancyLimits;
export const setRewardABI = setReward;
export const setRulesABI = setRules;
export const setSubscriptionIdABI = setSubscriptionId;
export const startRoundABI = startRound;
export const topUpABI = topUp;
export const transferABI = transfer;
export const transferAndCallABI = transferAndCall;
export const transferERC20ABI = transferERC20;
export const transferOwnershipABI = transferOwnership;
export const unBlacklistABI = unBlacklist;
export const unWhitelistABI = unWhitelist;
export const unWhitelistChildABI = unWhitelistChild;
export const unpackABI = unpack;
export const unpauseABI = unpause;
export const updateRuleABI = updateRule;
export const upgradeABI = upgrade;
export const userOfABI = userOf;
export const whiteListChildABI = whiteListChild;
export const whitelistABI = whitelist;
export const withdrawBalanceABI = withdrawBalance;
export const withdrawTokenABI = withdrawToken;
