import addConsumerVRFCoordinatorV2Mock from "./abis/addConsumer/VRFCoordinatorV2Mock.json";
import approveBEP20Token from "./abis/approve/BEP20Token.json";
import approveERC20 from "./abis/approve/ERC20.json";
import approveERC20Blacklist from "./abis/approve/ERC20Blacklist.json";
import approveERC721Blacklist from "./abis/approve/ERC721Blacklist.json";
import approveERC998Blacklist from "./abis/approve/ERC998Blacklist.json";
import approveLinkToken from "./abis/approve/LinkToken.json";
import approveStandardToken from "./abis/approve/StandardToken.json";
import approveWETH9 from "./abis/approve/WETH9.json";
import balanceOfBEP20Token from "./abis/balanceOf/BEP20Token.json";
import balanceOfBasicToken from "./abis/balanceOf/BasicToken.json";
import balanceOfERC1155Blacklist from "./abis/balanceOf/ERC1155Blacklist.json";
import balanceOfERC20 from "./abis/balanceOf/ERC20.json";
import balanceOfERC20Blacklist from "./abis/balanceOf/ERC20Blacklist.json";
import balanceOfERC721Blacklist from "./abis/balanceOf/ERC721Blacklist.json";
import balanceOfWETH9 from "./abis/balanceOf/WETH9.json";
import blacklistERC1155Blacklist from "./abis/blacklist/ERC1155Blacklist.json";
import breedExchangeBreedFacet from "./abis/breed/ExchangeBreedFacet.json";
import claimExchangeClaimFacet from "./abis/claim/ExchangeClaimFacet.json";
import claimWaitList from "./abis/claim/WaitList.json";
import craftExchangeCraftFacet from "./abis/craft/ExchangeCraftFacet.json";
import createSubscriptionVRFCoordinatorV2Mock from "./abis/createSubscription/VRFCoordinatorV2Mock.json";
import deployCollectionCollectionFactoryFacet from "./abis/deployCollection/CollectionFactoryFacet.json";
import deployERC1155TokenERC1155FactoryFacet from "./abis/deployERC1155Token/ERC1155FactoryFacet.json";
import deployERC20TokenERC20FactoryFacet from "./abis/deployERC20Token/ERC20FactoryFacet.json";
import deployERC721TokenERC721FactoryFacet from "./abis/deployERC721Token/ERC721FactoryFacet.json";
import deployERC998TokenERC998FactoryFacet from "./abis/deployERC998Token/ERC998FactoryFacet.json";
import deployLotteryLotteryFactoryFacet from "./abis/deployLottery/LotteryFactoryFacet.json";
import deployMysteryboxMysteryBoxFactoryFacet from "./abis/deployMysterybox/MysteryBoxFactoryFacet.json";
import deployPaymentSplitterPaymentSplitterFactoryFacet from "./abis/deployPaymentSplitter/PaymentSplitterFactoryFacet.json";
import deployPonziPonziFactoryFacet from "./abis/deployPonzi/PonziFactoryFacet.json";
import deployRaffleRaffleFactoryFacet from "./abis/deployRaffle/RaffleFactoryFacet.json";
import deployStakingStakingFactoryFacet from "./abis/deployStaking/StakingFactoryFacet.json";
import deployVestingVestingFactoryFacet from "./abis/deployVesting/VestingFactoryFacet.json";
import deployWaitListWaitListFactoryFacet from "./abis/deployWaitList/WaitListFactoryFacet.json";
import depositPonzi from "./abis/deposit/Ponzi.json";
import depositPonziBasic from "./abis/deposit/PonziBasic.json";
import depositReentrancyStakingReward from "./abis/deposit/ReentrancyStakingReward.json";
import depositStaking from "./abis/deposit/Staking.json";
import depositWETH9 from "./abis/deposit/WETH9.json";
import dismantleExchangeDismantleFacet from "./abis/dismantle/ExchangeDismantleFacet.json";
import disperseDispenser from "./abis/disperse/Dispenser.json";
import endRoundLotteryRandom from "./abis/endRound/LotteryRandom.json";
import getERC20ERC998ERC1155ERC20Enum from "./abis/getERC20/ERC998ERC1155ERC20Enum.json";
import getPenaltyStaking from "./abis/getPenalty/Staking.json";
import getPrizeLotteryRandom from "./abis/getPrize/LotteryRandom.json";
import getSubscriptionVRFCoordinatorV2Mock from "./abis/getSubscription/VRFCoordinatorV2Mock.json";
import grantRoleAccessControlFacet from "./abis/grantRole/AccessControlFacet.json";
import lendExchangeRentableFacet from "./abis/lend/ExchangeRentableFacet.json";
import mintBEP20Token from "./abis/mint/BEP20Token.json";
import mintBoxERC721MysteryBoxBlacklist from "./abis/mintBox/ERC721MysteryBoxBlacklist.json";
import mintBoxERC721Wrapper from "./abis/mintBox/ERC721Wrapper.json";
import mintCommonERC721Blacklist from "./abis/mintCommon/ERC721Blacklist.json";
import mintCommonERC721Genes from "./abis/mintCommon/ERC721Genes.json";
import mintERC1155Blacklist from "./abis/mint/ERC1155Blacklist.json";
import mintERC20Blacklist from "./abis/mint/ERC20Blacklist.json";
import mintERC721Blacklist from "./abis/mint/ERC721Blacklist.json";
import mintERC721CBlacklist from "./abis/mint/ERC721CBlacklist.json";
import mintERC721LotteryTicket from "./abis/mint/ERC721LotteryTicket.json";
import pausePausable from "./abis/pause/Pausable.json";
import pausePausableFacet from "./abis/pause/PausableFacet.json";
import purchaseExchangePurchaseFacet from "./abis/purchase/ExchangePurchaseFacet.json";
import purchaseLotteryExchangeLotteryFacet from "./abis/purchaseLottery/ExchangeLotteryFacet.json";
import purchaseMysteryExchangeMysteryBoxFacet from "./abis/purchaseMystery/ExchangeMysteryBoxFacet.json";
import purchaseRaffleExchangeRaffleFacet from "./abis/purchaseRaffle/ExchangeRaffleFacet.json";
import receiveRewardReentrancyStakingReward from "./abis/receiveReward/ReentrancyStakingReward.json";
import releasableGemunionSplitter from "./abis/releasable/GemunionSplitter.json";
import releasableVesting from "./abis/releasable/Vesting.json";
import releaseFundsLotteryRandom from "./abis/releaseFunds/LotteryRandom.json";
import releaseGemunionSplitter from "./abis/release/GemunionSplitter.json";
import releaseVesting from "./abis/release/Vesting.json";
import renounceRoleAccessControlFacet from "./abis/renounceRole/AccessControlFacet.json";
import revokeRoleAccessControlFacet from "./abis/revokeRole/AccessControlFacet.json";
import safeTransferChildERC998Blacklist from "./abis/safeTransferChild/ERC998Blacklist.json";
import safeTransferFromERC1155Blacklist from "./abis/safeTransferFrom/ERC1155Blacklist.json";
import safeTransferFromERC1155ERC998ERC1155ERC20Enum from "./abis/safeTransferFromERC1155/ERC998ERC1155ERC20Enum.json";
import safeTransferFromERC721Blacklist from "./abis/safeTransferFrom/ERC721Blacklist.json";
import setApprovalForAllERC1155Blacklist from "./abis/setApprovalForAll/ERC1155Blacklist.json";
import setDefaultRoyaltyERC1155Blacklist from "./abis/setDefaultRoyalty/ERC1155Blacklist.json";
import setPregnancyLimitsExchangeBreedFacet from "./abis/setPregnancyLimits/ExchangeBreedFacet.json";
import setRewardWaitList from "./abis/setReward/WaitList.json";
import setRulesPonzi from "./abis/setRules/Ponzi.json";
import setRulesStaking from "./abis/setRules/Staking.json";
import setSubscriptionIdERC721GenesBesu from "./abis/setSubscriptionId/ERC721GenesBesu.json";
import startRoundLotteryRandom from "./abis/startRound/LotteryRandom.json";
import topUpExchangeMockFacet from "./abis/topUp/ExchangeMockFacet.json";
import transferAndCallERC20Blacklist from "./abis/transferAndCall/ERC20Blacklist.json";
import transferAndCallERC677 from "./abis/transferAndCall/ERC677.json";
import transferAndCallERC677Token from "./abis/transferAndCall/ERC677Token.json";
import transferBEP20Token from "./abis/transfer/BEP20Token.json";
import transferBasicToken from "./abis/transfer/BasicToken.json";
import transferERC20 from "./abis/transfer/ERC20.json";
import transferERC20Blacklist from "./abis/transfer/ERC20Blacklist.json";
import transferERC20ERC998ERC1155ERC20Enum from "./abis/transferERC20/ERC998ERC1155ERC20Enum.json";
import transferLinkToken from "./abis/transfer/LinkToken.json";
import transferOwnershipBEP20Token from "./abis/transferOwnership/BEP20Token.json";
import transferOwnershipBasicToken from "./abis/transferOwnership/BasicToken.json";
import transferOwnershipERC20Ownable from "./abis/transferOwnership/ERC20Ownable.json";
import transferOwnershipOwnershipFacet from "./abis/transferOwnership/OwnershipFacet.json";
import transferOwnershipVRFCoordinatorV2Mock from "./abis/transferOwnership/VRFCoordinatorV2Mock.json";
import transferWETH9 from "./abis/transfer/WETH9.json";
import unBlacklistERC1155Blacklist from "./abis/unBlacklist/ERC1155Blacklist.json";
import unWhitelistChildERC998Blacklist from "./abis/unWhitelistChild/ERC998Blacklist.json";
import unWhitelistERC20Whitelist from "./abis/unWhitelist/ERC20Whitelist.json";
import unpackERC721MysteryBoxBlacklist from "./abis/unpack/ERC721MysteryBoxBlacklist.json";
import unpackWrapperMock from "./abis/unpack/WrapperMock.json";
import unpausePausable from "./abis/unpause/Pausable.json";
import unpausePausableFacet from "./abis/unpause/PausableFacet.json";
import updateRulePonzi from "./abis/updateRule/Ponzi.json";
import upgradeERC721BlacklistDiscrete from "./abis/upgrade/ERC721BlacklistDiscrete.json";
import upgradeExchangeGradeFacet from "./abis/upgrade/ExchangeGradeFacet.json";
import userOfERC721BlacklistDiscreteRentable from "./abis/userOf/ERC721BlacklistDiscreteRentable.json";
import whiteListChildERC998Blacklist from "./abis/whiteListChild/ERC998Blacklist.json";
import whitelistERC20Whitelist from "./abis/whitelist/ERC20Whitelist.json";
import withdrawBalanceReentrancyStakingReward from "./abis/withdrawBalance/ReentrancyStakingReward.json";
import withdrawTokenPonzi from "./abis/withdrawToken/Ponzi.json";

export const addConsumerVRFCoordinatorV2MockABI = addConsumerVRFCoordinatorV2Mock;
export const approveBEP20TokenABI = approveBEP20Token;
export const approveERC20ABI = approveERC20;
export const approveERC20BlacklistABI = approveERC20Blacklist;
export const approveERC721BlacklistABI = approveERC721Blacklist;
export const approveERC998BlacklistABI = approveERC998Blacklist;
export const approveLinkTokenABI = approveLinkToken;
export const approveStandardTokenABI = approveStandardToken;
export const approveWETH9ABI = approveWETH9;
export const balanceOfBEP20TokenABI = balanceOfBEP20Token;
export const balanceOfBasicTokenABI = balanceOfBasicToken;
export const balanceOfERC1155BlacklistABI = balanceOfERC1155Blacklist;
export const balanceOfERC20ABI = balanceOfERC20;
export const balanceOfERC20BlacklistABI = balanceOfERC20Blacklist;
export const balanceOfERC721BlacklistABI = balanceOfERC721Blacklist;
export const balanceOfWETH9ABI = balanceOfWETH9;
export const blacklistERC1155BlacklistABI = blacklistERC1155Blacklist;
export const breedExchangeBreedFacetABI = breedExchangeBreedFacet;
export const claimExchangeClaimFacetABI = claimExchangeClaimFacet;
export const claimWaitListABI = claimWaitList;
export const craftExchangeCraftFacetABI = craftExchangeCraftFacet;
export const createSubscriptionVRFCoordinatorV2MockABI = createSubscriptionVRFCoordinatorV2Mock;
export const deployCollectionCollectionFactoryFacetABI = deployCollectionCollectionFactoryFacet;
export const deployERC1155TokenERC1155FactoryFacetABI = deployERC1155TokenERC1155FactoryFacet;
export const deployERC20TokenERC20FactoryFacetABI = deployERC20TokenERC20FactoryFacet;
export const deployERC721TokenERC721FactoryFacetABI = deployERC721TokenERC721FactoryFacet;
export const deployERC998TokenERC998FactoryFacetABI = deployERC998TokenERC998FactoryFacet;
export const deployLotteryLotteryFactoryFacetABI = deployLotteryLotteryFactoryFacet;
export const deployMysteryboxMysteryBoxFactoryFacetABI = deployMysteryboxMysteryBoxFactoryFacet;
export const deployPaymentSplitterPaymentSplitterFactoryFacetABI = deployPaymentSplitterPaymentSplitterFactoryFacet;
export const deployPonziPonziFactoryFacetABI = deployPonziPonziFactoryFacet;
export const deployRaffleRaffleFactoryFacetABI = deployRaffleRaffleFactoryFacet;
export const deployStakingStakingFactoryFacetABI = deployStakingStakingFactoryFacet;
export const deployVestingVestingFactoryFacetABI = deployVestingVestingFactoryFacet;
export const deployWaitListWaitListFactoryFacetABI = deployWaitListWaitListFactoryFacet;
export const depositPonziABI = depositPonzi;
export const depositPonziBasicABI = depositPonziBasic;
export const depositReentrancyStakingRewardABI = depositReentrancyStakingReward;
export const depositStakingABI = depositStaking;
export const depositWETH9ABI = depositWETH9;
export const dismantleExchangeDismantleFacetABI = dismantleExchangeDismantleFacet;
export const disperseDispenserABI = disperseDispenser;
export const endRoundLotteryRandomABI = endRoundLotteryRandom;
export const getERC20ERC998ERC1155ERC20EnumABI = getERC20ERC998ERC1155ERC20Enum;
export const getPenaltyStakingABI = getPenaltyStaking;
export const getPrizeLotteryRandomABI = getPrizeLotteryRandom;
export const getSubscriptionVRFCoordinatorV2MockABI = getSubscriptionVRFCoordinatorV2Mock;
export const grantRoleAccessControlFacetABI = grantRoleAccessControlFacet;
export const lendExchangeRentableFacetABI = lendExchangeRentableFacet;
export const mintBEP20TokenABI = mintBEP20Token;
export const mintBoxERC721MysteryBoxBlacklistABI = mintBoxERC721MysteryBoxBlacklist;
export const mintBoxERC721WrapperABI = mintBoxERC721Wrapper;
export const mintCommonERC721BlacklistABI = mintCommonERC721Blacklist;
export const mintCommonERC721GenesABI = mintCommonERC721Genes;
export const mintERC1155BlacklistABI = mintERC1155Blacklist;
export const mintERC20BlacklistABI = mintERC20Blacklist;
export const mintERC721BlacklistABI = mintERC721Blacklist;
export const mintERC721CBlacklistABI = mintERC721CBlacklist;
export const mintERC721LotteryTicketABI = mintERC721LotteryTicket;
export const pausePausableABI = pausePausable;
export const pausePausableFacetABI = pausePausableFacet;
export const purchaseExchangePurchaseFacetABI = purchaseExchangePurchaseFacet;
export const purchaseLotteryExchangeLotteryFacetABI = purchaseLotteryExchangeLotteryFacet;
export const purchaseMysteryExchangeMysteryBoxFacetABI = purchaseMysteryExchangeMysteryBoxFacet;
export const purchaseRaffleExchangeRaffleFacetABI = purchaseRaffleExchangeRaffleFacet;
export const receiveRewardReentrancyStakingRewardABI = receiveRewardReentrancyStakingReward;
export const releasableGemunionSplitterABI = releasableGemunionSplitter;
export const releasableVestingABI = releasableVesting;
export const releaseFundsLotteryRandomABI = releaseFundsLotteryRandom;
export const releaseGemunionSplitterABI = releaseGemunionSplitter;
export const releaseVestingABI = releaseVesting;
export const renounceRoleAccessControlFacetABI = renounceRoleAccessControlFacet;
export const revokeRoleAccessControlFacetABI = revokeRoleAccessControlFacet;
export const safeTransferChildERC998BlacklistABI = safeTransferChildERC998Blacklist;
export const safeTransferFromERC1155BlacklistABI = safeTransferFromERC1155Blacklist;
export const safeTransferFromERC1155ERC998ERC1155ERC20EnumABI = safeTransferFromERC1155ERC998ERC1155ERC20Enum;
export const safeTransferFromERC721BlacklistABI = safeTransferFromERC721Blacklist;
export const setApprovalForAllERC1155BlacklistABI = setApprovalForAllERC1155Blacklist;
export const setDefaultRoyaltyERC1155BlacklistABI = setDefaultRoyaltyERC1155Blacklist;
export const setPregnancyLimitsExchangeBreedFacetABI = setPregnancyLimitsExchangeBreedFacet;
export const setRewardWaitListABI = setRewardWaitList;
export const setRulesPonziABI = setRulesPonzi;
export const setRulesStakingABI = setRulesStaking;
export const setSubscriptionIdERC721GenesBesuABI = setSubscriptionIdERC721GenesBesu;
export const startRoundLotteryRandomABI = startRoundLotteryRandom;
export const topUpExchangeMockFacetABI = topUpExchangeMockFacet;
export const transferAndCallERC20BlacklistABI = transferAndCallERC20Blacklist;
export const transferAndCallERC677ABI = transferAndCallERC677;
export const transferAndCallERC677TokenABI = transferAndCallERC677Token;
export const transferBEP20TokenABI = transferBEP20Token;
export const transferBasicTokenABI = transferBasicToken;
export const transferERC20ABI = transferERC20;
export const transferERC20BlacklistABI = transferERC20Blacklist;
export const transferERC20ERC998ERC1155ERC20EnumABI = transferERC20ERC998ERC1155ERC20Enum;
export const transferLinkTokenABI = transferLinkToken;
export const transferOwnershipBEP20TokenABI = transferOwnershipBEP20Token;
export const transferOwnershipBasicTokenABI = transferOwnershipBasicToken;
export const transferOwnershipERC20OwnableABI = transferOwnershipERC20Ownable;
export const transferOwnershipOwnershipFacetABI = transferOwnershipOwnershipFacet;
export const transferOwnershipVRFCoordinatorV2MockABI = transferOwnershipVRFCoordinatorV2Mock;
export const transferWETH9ABI = transferWETH9;
export const unBlacklistERC1155BlacklistABI = unBlacklistERC1155Blacklist;
export const unWhitelistChildERC998BlacklistABI = unWhitelistChildERC998Blacklist;
export const unWhitelistERC20WhitelistABI = unWhitelistERC20Whitelist;
export const unpackERC721MysteryBoxBlacklistABI = unpackERC721MysteryBoxBlacklist;
export const unpackWrapperMockABI = unpackWrapperMock;
export const unpausePausableABI = unpausePausable;
export const unpausePausableFacetABI = unpausePausableFacet;
export const updateRulePonziABI = updateRulePonzi;
export const upgradeERC721BlacklistDiscreteABI = upgradeERC721BlacklistDiscrete;
export const upgradeExchangeGradeFacetABI = upgradeExchangeGradeFacet;
export const userOfERC721BlacklistDiscreteRentableABI = userOfERC721BlacklistDiscreteRentable;
export const whiteListChildERC998BlacklistABI = whiteListChildERC998Blacklist;
export const whitelistERC20WhitelistABI = whitelistERC20Whitelist;
export const withdrawBalanceReentrancyStakingRewardABI = withdrawBalanceReentrancyStakingReward;
export const withdrawTokenPonziABI = withdrawTokenPonzi;
