version: "3.3"

volumes:
  static-admin-ui:
  static-market-ui:

services:

  admin-ui:
    container_name: admin-ui
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "sh /home/node/framework/scripts/logDna.sh"
    volumes:
      - static-admin-ui:/home/node/framework/services/admin-ui/dist/
    environment:
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      BASE_MODE: "${BASE_MODE}"
      BASE_APP: "Admin-UI"

  market-ui:
    container_name: market-ui
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "sh /home/node/framework/scripts/logDna.sh"
    volumes:
      - static-market-ui:/home/node/framework/services/market-ui/dist/
    environment:
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      BASE_MODE: "${BASE_MODE}"
      BASE_APP: "market-UI"

  admin-api:
    container_name: admin-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./services/admin-api start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_ADMIN_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_QUEUE_EMAIL: "${RMQ_QUEUE_EMAIL}"
      # FE
      ADMIN_FE_URL: "${ADMIN_FE_URL}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      # BLOCKCHAIN
      CHAIN_ID: "${CHAIN_ID}"
      ACCOUNT: "${ACCOUNT}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      JSON_RPC_ADDR: "${JSON_RPC_ADDR}"
      WEBSOCKET_ADDR: "${WEBSOCKET_ADDR}"
      # Contracts
      CONTRACT_MANAGER_ADDR: "${CONTRACT_MANAGER_ADDR}"
      MARKETPLACE_ADDR: "${MARKETPLACE_ADDR}"
      EXCHANGE_ADDR: "${EXCHANGE_ADDR}"
      DROPBOX_ADDR: "${DROPBOX_ADDR}"
      AIRDROP_ADDR: "${AIRDROP_ADDR}"
    ports:
      # admin-api
      - "${PORT_ADMIN_API}:${PORT_ADMIN_API}"

  market-api:
    container_name: market-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./services/market-api start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_MARKET_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      RMQ_QUEUE_EMAIL: "${RMQ_QUEUE_EMAIL}"
      # FE
      MARKET_FE_URL: "${MARKET_FE_URL}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      # BLOCKCHAIN
      CHAIN_ID: "${CHAIN_ID}"
      ACCOUNT: "${ACCOUNT}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      JSON_RPC_ADDR: "${JSON_RPC_ADDR}"
      WEBSOCKET_ADDR: "${WEBSOCKET_ADDR}"
      # Contracts
      CONTRACT_MANAGER_ADDR: "${CONTRACT_MANAGER_ADDR}"
      MARKETPLACE_ADDR: "${MARKETPLACE_ADDR}"
      EXCHANGE_ADDR: "${EXCHANGE_ADDR}"
      DROPBOX_ADDR: "${DROPBOX_ADDR}"
      AIRDROP_ADDR: "${AIRDROP_ADDR}"
    ports:
      # market-api
      - "${PORT_MARKET_API}:${PORT_MARKET_API}"

  core-eth:
    container_name: core-eth
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./services/core-eth start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_RPC_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
      # RMQ
      RMQ_URL: "${RMQ_URL}"
      # FE
      FE_URL: "${ADMIN_FE_URL}"
      # LOGDNA
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      # BLOCKCHAIN
      CHAIN_ID: "${CHAIN_ID}"
      ACCOUNT: "${ACCOUNT}"
      PRIVATE_KEY: "${PRIVATE_KEY}"
      JSON_RPC_ADDR: "${JSON_RPC_ADDR}"
      WEBSOCKET_ADDR: "${WEBSOCKET_ADDR}"
      LATENCY: "${LATENCY}"
      STARTING_BLOCK: "${STARTING_BLOCK}"
      # Contracts
      CONTRACT_MANAGER_ADDR: "${CONTRACT_MANAGER_ADDR}"
      MARKETPLACE_ADDR: "${MARKETPLACE_ADDR}"
      EXCHANGE_ADDR: "${EXCHANGE_ADDR}"
      DROPBOX_ADDR: "${DROPBOX_ADDR}"
      AIRDROP_ADDR: "${AIRDROP_ADDR}"
    ports:
      - "${PORT_RPC_API}:${PORT_RPC_API}"

  json-api:
    container_name: json-api
    image: gcr.io/halogen-framing-335807/framework-img:latest
    command: "npm run --prefix ./microservices/json start:${BASE_MODE}"
    environment:
      # common
      BASE_MODE: "${BASE_MODE}"
      NODE_ENV: "${NODE_ENV}"
      HOST: "${HOST}"
      PORT: "${PORT_JSON_API}"
      # admin api
      POSTGRES_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
      # REDIS
      REDIS_THROTTLE_URL: "${REDIS_THROTTLE_URL}"
      # THROTTLE
      THROTTLE_TTL: "${THROTTLE_TTL}"
      THROTTLE_LIMIT: "${THROTTLE_LIMIT}"
      LOGDNA_INGESTION_KEY: "${LOGDNA_INGESTION_KEY}"
      # GEMUNION
      GEMUNION_API_KEY: "${GEMUNION_API_KEY}"
    ports:
      # admin-api
      - "${PORT_JSON_API}:${PORT_JSON_API}"

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/admin.${BASE_MODE}.conf:/etc/nginx/conf.d/admin.conf
      - ./nginx/log:/var/log/nginx/
      - type: volume
        source: static-admin-ui
        target: /var/www/admin-ui/static
        volume:
          nocopy: true
      - type: volume
        source: static-market-ui
        target: /var/www/market-ui/static
        volume:
          nocopy: true
    ports:
      - "80:80"
      - "443:443"
      - "1337:1337"
    depends_on:
      - admin-api
      - admin-ui
      - market-ui
      - market-api
      - json-api
      - core-eth
