FROM node:16-alpine AS base
LABEL stage=base

RUN apk add \
  python \
  build-base \
  git \
  bash \
  curl \
  gettext \
  nano \
  && npm i -g node-gyp

FROM base AS deps
LABEL stage=deps

USER node
RUN mkdir -p /home/node/framework
WORKDIR /home/node/framework

COPY --chown=node:node . .

RUN npx lerna bootstrap --hoist
RUN npm cache clean --force

FROM base as prod
USER node
WORKDIR /home/node/framework
COPY --from=deps --chown=node:node /home/node/framework/. .
