export enum WatcherInType {
  CREATE_TRANSACTION_LISTENER = "CREATE_TRANSACTION_LISTENER",
  REMOVE_TRANSACTION_LISTENER = "REMOVE_TRANSACTION_LISTENER",
}

export enum WatcherOutType {
  TRANSACTION_MINED = "TRANSACTION_MINED",
  TRANSACTION_CONFIRMED = "TRANSACTION_CONFIRMED",
  TRANSACTION_ERRORED = "TRANSACTION_ERRORED",
}
