export enum ContractType {
  CONTRACT_MANAGER = "CONTRACT_MANAGER",
  EXCHANGE = "EXCHANGE",

  ACCESS_CONTROLL = "ACCESS_CONTROLL",
  ACCESS_LIST = "ACCESS_LIST",
  PAUSE = "PAUSE",
  BASE_URL = "BASE_URL",
  ROYALTY = "ROYALTY",
  METADATA = "METADATA",

  ERC20_TOKEN = "ERC20_TOKEN",
  ERC721_TOKEN = "ERC721_TOKEN",
  ERC998_TOKEN = "ERC998_TOKEN",
  ERC1155_TOKEN = "ERC1155_TOKEN",

  RENTABLE = "RENTABLE",
  DESCRETE = "DESCRETE",
  COLLECTION = "COLLECTION",

  WRAPPER = "WRAPPER",
  LOOT = "LOOT",
  MYSTERY = "MYSTERY",
  WAIT_LIST = "WAIT_LIST",
  PAYMENT_SPLITTER = "PAYMENT_SPLITTER",
  PONZI = "PONZI",
  CLAIM = "CLAIM",
  STAKING = "STAKING",
  VESTING = "VESTING",
  LOTTERY = "LOTTERY",
  RAFFLE = "RAFFLE",
  PREDICTION = "PREDICTION",

  REFERRAL = "REFERRAL",

  VRF = "VRF",
  RANDOM = "RANDOM",
}
