export enum SwapStatus {
  DORMANT = "DORMANT",
  PREPARING_TX = "PREPARING_TX",
  AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION",
  AWAITING_APPROVAL = "AWAITING_APPROVAL",
  AWAITING_APPROVE_TX = "AWAITING_APPROVE_TX",
  SENDING_TX = "SENDING_TX",
  COMPLETE = "COMPLETE",
  ERROR = "ERROR",
}
