export enum EmailType {
  DUMMY = "DUMMY",
  FEEDBACK = "FEEDBACK",
  LINK_TOKEN = "LINK_TOKEN",
  CONTACT = "CONTACT",
  INVITE = "INVITE",
}

export enum ContactType {
  REQUEST_DEMO = "REQUEST_DEMO",
  PARTNERSHIP = "PARTNERSHIP",
  GET_QUOTATION = "GET_QUOTATION",
  APPLY_FOR_TIER = "APPLY_FOR_TIER",
}
