export enum MobileEventType {
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",

  TOKEN_TRANSFER = "TOKEN_TRANSFER",
  BATCH_TRANSFER = "BATCH_TRANSFER",

  PURCHASE = "PURCHASE",
  PURCHASE_RANDOM = "PURCHASE_RANDOM",
  PURCHASE_MYSTERY = "PURCHASE_MYSTERY",
  PURCHASE_RAFFLE = "PURCHASE_RAFFLE",
  PURCHASE_LOTTERY = "PURCHASE_LOTTERY",

  LOTTERY_PRIZE = "LOTTERY_PRIZE",
  LOTTERY_FINALIZE = "LOTTERY_FINALIZE",
  LOTTERY_ROUND_START = "LOTTERY_ROUND_START",
  LOTTERY_ROUND_END = "LOTTERY_ROUND_END",

  RAFFLE_PRIZE = "RAFFLE_PRIZE",
  RAFFLE_FINALIZE = "RAFFLE_FINALIZE",
  RAFFLE_ROUND_START = "RAFFLE_ROUND_START",
  RAFFLE_ROUND_END = "RAFFLE_ROUND_END",

  STAKING_DEPOSIT_START = "STAKING_DEPOSIT_START",
  STAKING_DEPOSIT_FINISH = "STAKING_DEPOSIT_FINISH",
  STAKING_RULE_CREATED = "STAKING_RULE_CREATED",
  STAKING_RULE_UPDATED = "STAKING_RULE_UPDATED",

  BREED = "BREED",
  CLAIM = "CLAIM",
  CRAFT = "CRAFT",
  DISMANTLE = "DISMANTLE",
  RENT = "RENT",
  RENT_USER = "RENT_USER",
  UPGRADE = "UPGRADE",
  WAITLIST_REWARD_SET = "WAITLIST_REWARD_SET",
  WAITLIST_REWARD_CLAIMED = "WAITLIST_REWARD_CLAIMED",
  VESTING_RELEASED = "VESTING_RELEASED",
}

export interface IMessage {
  from: string;
  to: string;
  value: string;
  transactionHash: string;
}
