export enum RmqProviderType {
  EML_SERVICE = "EML_SERVICE",
  WEBHOOK_SERVICE = "WEBHOOK_SERVICE",
  WATCHER_IN_SERVICE = "WATCHER_IN_SERVICE",
  WATCHER_OUT_SERVICE = "WATCHER_OUT_SERVICE",
  MOBILE_SERVICE = "MOBILE_SERVICE",
  SCHEDULE_SERVICE = "SCHEDULE_SERVICE",
}
