export enum RmqProviderType {
  EML_SERVICE = "EML_SERVICE",
  WEBHOOK_SERVICE = "WEBHOOK_SERVICE",
  CRON_SERVICE = "CRON_SERVICE",
  MOBILE_SERVICE = "MOBILE_SERVICE",
  GAME_SERVICE = "GAME_SERVICE",
  SIGNAL_SERVICE = "SIGNAL_SERVICE",
}
