export enum ProviderType {
  WAREHOUSE_SERVICE = "WAREHOUSE_SERVICE",
  EML_SERVICE = "EML_SERVICE",
  TPL_SERVICE = "TPL_SERVICE",
  PDF_SERVICE = "PDF_SERVICE",
  WEBHOOK_SERVICE = "WEBHOOK_SERVICE",
  SES = "SES",
  S3 = "S3",
}
