name: Test & Deploy master
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  ci-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres:alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: framework-test
          POSTGRES_PORT: 5432
        ports: [ "5432:5432" ]
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # SETUP NODE JS VERSION
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Authenticate Registry & Configure Git User
        run: |
          echo "@gemunion:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUBTOKEN" >> .npmrc
          git update-index --assume-unchanged .npmrc
          npx npm-cli-login -u $GITHUBUSER -p $GITHUBTOKEN -e $GITHUBEMAIL -r https://npm.pkg.github.com -s @gemunion --config-path="./"
          git config --global user.name '@gemunion'
          git config --global user.email $GITHUBEMAIL
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUBUSER: ${{ secrets.GITHUBUSER }}
          GITHUBEMAIL: ${{ secrets.GITHUBEMAIL }}


      - name: Authenticate check via npm
        run: npm whoami --registry=https://npm.pkg.github.com/

      - name: Install Packages
        run: npm i

      - name: Npm run test
        run: npm run test
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NODE_ENV: test
          TEST_CONTRACTS: false
          BUSINESS_TYPE: B2B
          POSTGRES_URL: 'postgres://postgres:postgres@0.0.0.0:5432/framework-test'
          CHAIN_ID: 10001
          GEMUNION_API_KEY: ${{ secrets.GEMUNION_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY1: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY2: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY3: ${{ secrets.PRIVATE_KEY }}
          GEMUNION_PRIVATE_KEY_STAGE: ${{ secrets.PRIVATE_KEY }}
          GEMUNION_PRIVATE_KEY_PROD: ${{ secrets.PRIVATE_KEY }}
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}

  cloudbuild-deploy:
    needs: ci-test
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook cloud-build deploy
        run: |
          curl --request POST --url $CLOUDBUILD_WEBHOOK_URL --header "content-type: application/json"
        env:
          CLOUDBUILD_WEBHOOK_URL: ${{ secrets.CLOUDBUILD_WEBHOOK_URL }}

#  telegram-notify-start:
#    needs: cloudbuild-deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: Send message to Telegram
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_CHAT }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          format: html
#          message: |
#            The manual dispatch event triggered Cloud-build Deploy action.
#
