
name: Maintenance Trigger (ON|OFF)
on:
  workflow_dispatch:
    inputs:
      command:
        description: on || off
        default: on
        required: true

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'test gcloud CLI'
        run: 'gcloud info'

      - name: 'set mode ON'
        if: ${{ github.event.inputs.command == 'on' }}
        run: 'gcloud compute url-maps add-path-matcher portal-https-lb --path-matcher-name=path-matcher-4 --default-backend-bucket=https://www.googleapis.com/compute/v1/projects/halogen-framing-335807/global/backendBuckets/static-failover --existing-host=admin.gemunion.io --delete-orphaned-path-matcher'
      - name: 'set mode OFF'
        if: ${{ github.event.inputs.command == 'off' }}
        run: 'gcloud compute url-maps add-path-matcher portal-https-lb --path-matcher-name=path-matcher-4 --default-service=https://www.googleapis.com/compute/v1/projects/halogen-framing-335807/global/backendServices/framework-be --existing-host=admin.gemunion.io --delete-orphaned-path-matcher'
